---
name: Master CI PR Workflow
on:
  pull_request:
    branches:
      - 'main'
      - 'rel-*'
      - 'TS-*'
      - 'SRE-*'
      - 'TOPS-*'
      - 'revert-*'
      - 'TDEVOPS-*'
      - 'TITO-*'

jobs:
  master-ci-pr:
    uses: ./.github/workflows/master_pr.yml
    secrets: inherit
